chat-prefix: [MineTinker]

logging:
  standard: false #logs important player activities with MineTinker
  debug: false #even more information
  metrics: true

chat-messages: true #Will turn off command output
actionbar-messages: true

LevelStep: 100 #  *(LevelFactor^LevelOfTool)
LevelFactor: 2.0
ResetAtVarOverflow: true #Resets Level and Exp at Integer.MAX_VALUE or Long.MAX_VALUE with 1 and 0. false: no more Exp gain
AddModifierSlotsPerLevel: 1
StartingModifierSlots: 1
ExpPerBlockBreak: 1 #How much XP will the tool get when you break a block
ExpPerEntityHit: 1 #How much XP will the tool get when you hit a Entity with Sword / Bow
ExpPerArrowShot: 1 #How much XP will the tool get when you shoot with the bow
EnableDamageExp: false #When true: Sword/Bow will gain XP equal to the damage-value
Upgradeable: true #Can you upgrade your tools with an anvil
Repairable: true #Can you repair your tools in your inventory (instead of an anvil) just by dragging the ressource on the tool
AllowEnchanting: false #When enabled you can enchant the tools with vanilla methods (not recommended!)
AllowCrafting: true #Only recommended if used in combination with other Plugins that use the crafting grid for tools. If false: Tools are only aquired with give command
DurabilityPercentageRepair: 0.34 #How much durability (relative to maximum durability) should the tool recover per item

LevelUpEvents:
  enabled: true
  DurabilityRepair: #Repairs the tool
    enabled: true
    percentage: 50
  RandomModifier: #Applies a random modifier
    enabled: true
    percentage: 10
  DropLoot: #Drops specific loot
    enabled: true
    percentage: 25
    minimumDrop: 1
    maximumDrop: 5
    Items:
      - DIAMOND
      - IRON_INGOT
      - GOLD_INGOT
      - EMERALD
  DropXP: #Drops a certain amout of XP
    enabled: true
    percentage: 25
    amount: 100

Sound:
  OnLevelUp: true
  OnCrafting: true
  OnEveryCrafting: false
  OnModding: true
  OnFail: true
  OnEnchanting: true
  OnUpgrade: true
  OnBreaking: true

AllowedWorlds: #Worlds where MineTinker-Tools can be used
  - world #default
  - world_nether #default
  - world_the_end #default

Spawners:
  enabled: true #Should be disabled when using a different Spawner plugin
  onlyWithSilkTouch: true
  AllowedWorlds: #Worlds where Spawners can be mined and placed
    - world #default
    - world_nether #default
    - world_the_end #default

EasyHarvest:
  enabled: true
  replant: true
  Sound: true
  AllowedWorlds: #Worlds where MineTinker-Builderswands can be used
    - world #default
    - world_nether #default
    - world_the_end #default

Language:
  #Tool
  Identifier_Armor: MineTinker-Armor
  Identifier_Builderswand: MineTinker-Builderswand
  Identifier_Tool: MineTinker-Tool
  LevelLine: Level
  ExpLine: Exp
  FreeModifierSlotsLine: Free Modifiers Slots
  ModifiersLine: Modifiers
  Commands:
    InvalidArguments: Invalid arguments!
    InvalidTool: Invalid tool!
    NoPermission: You do not have permission to use this command!
    NotAPlayer: This is a player only command!
